import type { AssetCatalog } from './types.js';

export const catalog: AssetCatalog = {
  version: '1.0.0',
  generatedAt: '2026-08-08T00:00:00.000Z',
  assets: [
    {
      id: 'world',
      name: 'World',
      tags: ['area', 'outdoor', 'root'],
      source: { type: 'canonical' },
      glb: { generated: false },
      svg: { generated: false },
      sprite: { generated: false },
      boundingBox: { width: 1000, height: 1000, depth: 1000 },
      hotspots: [],
      materials: [],
      scale: 1
    },
    {
      id: 'house',
      name: 'House',
      tags: ['area', 'indoor', 'building'],
      source: { type: 'canonical' },
      glb: { generated: false },
      svg: { generated: false },
      sprite: { generated: false },
      boundingBox: { width: 12, height: 6, depth: 10 },
      hotspots: [],
      materials: [],
      scale: 1
    },
    {
      id: 'kitchen',
      name: 'Kitchen',
      tags: ['area', 'indoor', 'room'],
      source: { type: 'canonical' },
      glb: { generated: false },
      svg: { generated: false },
      sprite: { generated: false },
      boundingBox: { width: 5, height: 3, depth: 4 },
      hotspots: [],
      materials: [],
      scale: 1
    },
    {
      id: 'refrigerator',
      name: 'Refrigerator',
      tags: ['appliance', 'kitchen', 'food-storage'],
      source: { type: 'canonical' },
      glb: { generated: false },
      svg: { generated: false },
      sprite: { generated: false },
      boundingBox: { width: 1, height: 2, depth: 0.8 },
      hotspots: [],
      materials: [],
      scale: 1
    },
    {
      id: 'stove',
      name: 'Stove',
      tags: ['appliance', 'kitchen', 'cooking'],
      source: { type: 'canonical' },
      glb: { generated: false },
      svg: { generated: false },
      sprite: { generated: false },
      boundingBox: { width: 0.9, height: 0.9, depth: 0.8 },
      hotspots: [],
      materials: [],
      scale: 1
    },
    {
      id: 'counter',
      name: 'Counter',
      tags: ['furniture', 'kitchen', 'surface'],
      source: { type: 'canonical' },
      glb: { generated: false },
      svg: { generated: false },
      sprite: { generated: false },
      boundingBox: { width: 2.4, height: 0.95, depth: 0.65 },
      hotspots: [],
      materials: [],
      scale: 1
    },
    {
      id: 'sink',
      name: 'Sink',
      tags: ['appliance', 'kitchen', 'plumbing'],
      source: { type: 'canonical' },
      glb: { generated: false },
      svg: { generated: false },
      sprite: { generated: false },
      boundingBox: { width: 0.7, height: 0.3, depth: 0.5 },
      hotspots: [],
      materials: [],
      scale: 1
    },
    {
      id: 'cabinet',
      name: 'Cabinet',
      tags: ['furniture', 'kitchen', 'storage'],
      source: { type: 'canonical' },
      glb: { generated: false },
      svg: { generated: false },
      sprite: { generated: false },
      boundingBox: { width: 0.8, height: 1.2, depth: 0.6 },
      hotspots: [],
      materials: [],
      scale: 1
    },
    {
      id: 'sofa',
      name: 'Sofa',
      tags: ['furniture', 'living-room', 'seating'],
      source: { type: 'canonical' },
      glb: { generated: false },
      svg: { generated: false },
      sprite: { generated: false },
      boundingBox: { width: 2.2, height: 0.85, depth: 0.95 },
      hotspots: [],
      materials: [],
      scale: 1
    },
    {
      id: 'coffee-table',
      name: 'Coffee Table',
      tags: ['furniture', 'living-room', 'table'],
      source: { type: 'canonical' },
      glb: { generated: false },
      svg: { generated: false },
      sprite: { generated: false },
      boundingBox: { width: 1.2, height: 0.45, depth: 0.7 },
      hotspots: [],
      materials: [],
      scale: 1
    },
    {
      id: 'rug',
      name: 'Rug',
      tags: ['decor', 'living-room', 'floor'],
      source: { type: 'canonical' },
      glb: { generated: false },
      svg: { generated: false },
      sprite: { generated: false },
      boundingBox: { width: 2.5, height: 0.05, depth: 1.8 },
      hotspots: [],
      materials: [],
      scale: 1
    },
    {
      id: 'tree',
      name: 'Tree',
      tags: ['nature', 'outdoor', 'flora'],
      source: { type: 'canonical' },
      glb: { generated: false },
      svg: { generated: false },
      sprite: { generated: false },
      boundingBox: { width: 2, height: 4, depth: 2 },
      hotspots: [],
      materials: [],
      scale: 1
    },
    {
      id: 'path',
      name: 'Path',
      tags: ['outdoor', 'ground', 'walkway'],
      source: { type: 'canonical' },
      glb: { generated: false },
      svg: { generated: false },
      sprite: { generated: false },
      boundingBox: { width: 3, height: 0.1, depth: 15 },
      hotspots: [],
      materials: [],
      scale: 1
    },
    {
      id: 'wall',
      name: 'Wall',
      tags: ['structure', 'indoor', 'boundary'],
      source: { type: 'canonical' },
      glb: { generated: false },
      svg: { generated: false },
      sprite: { generated: false },
      boundingBox: { width: 0.2, height: 3, depth: 6 },
      hotspots: [],
      materials: [],
      scale: 1
    },
    {
      id: 'window',
      name: 'Window',
      tags: ['structure', 'indoor', 'opening'],
      source: { type: 'canonical' },
      glb: { generated: false },
      svg: { generated: false },
      sprite: { generated: false },
      boundingBox: { width: 1.2, height: 1.2, depth: 0.1 },
      hotspots: [],
      materials: [],
      scale: 1
    },
    {
      id: 'ground',
      name: 'Ground',
      tags: ['outdoor', 'terrain', 'base'],
      source: { type: 'canonical' },
      glb: { generated: false },
      svg: { generated: false },
      sprite: { generated: false },
      boundingBox: { width: 500, height: 1, depth: 500 },
      hotspots: [],
      materials: [],
      scale: 1
    }
  ]
};
